services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: timeseriesdb
      POSTGRES_USER: timescaledb
      POSTGRES_PASSWORD: password
      TIMESCALEDB_TELEMETRY: 'off'
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U timescaledb']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  timescaledb_data:
    driver: local
